---
title: "Course Reflection"
format: html
---

Reading through my weekly reflections, I notice a change in my thought process throughout the course. In the beginning of the course, I focused on individual topics themselves, like the atmosphere, soil, primary production, etc. As the course continued, I notice that I began to look at connections between different ecosystems (for example, in Reflection 9, I discussed how lakes and streams have different spatial separation of processes, but how the biogeochemical patterns between the two are similar). I also notice that my reflections began to examine mechanisms more closely rather than just repeating information that I had learned (for example, in Reflection 13 I discussed how MRT and the paradox of enrichment relate to carbon accumulation in the atmosphere). While I learned a lot of new material, I think the most important thing that I learned was how to practice systems thinking in real-world contexts.

While reflecting on the formulation of my GRFP proposal, I tried to pinpoint what exactly got me excited about soil and microbes. Prior to this course, I was a big advocate for soil health and was interested in microbes because my capstone project was on extremophiles, but I had never considered studying them. Our discussions in class about soils and soil microbes changed the way I viewed the topic, opening my eyes to a mysterious and robust unseen world beneath the ground! I became interested in uniting the previous research I had done on indaziflam with soil microbes, and landed on my GRFP topic. I was curious how physical properties of soil discussed in class, such as cation-exchange capactiy and reactive nitrogen in soil are affected by indaziflam, as well as how these changes impact microbial community composition. I was also curious if changes to microbial communities are more influenced by indaziflam itself and its metabolites, or shifting plant communities, like we saw in the Arctic case study in which fertilizer was applied.

Looking back at what we discussed throughout the semester, this course honestly felt more like a capstone course than the actual capstone course for ESS. The following are the biggest takeaways that I got from this course, that I believe will influence the way I approach future academic and professional endeavors:

1\) Residence time and rate of change: I learned why rate of emissions is more informative than simply looking at amounts alone. For example, the MRT of CO2 in the atmosphere is quite high compared to the rate of emissions. Because the emissions rate is so high, even if we drastically cut emissions, the effects of human-facilitated CO2 release to the atmosphere will be felt for centuries, as already emitted CO2 will stick around in the atmosphere for a long time.

2\) Designing experiments: Several times, Dr. Moore prompted us to think of an experiment to measure a certain phenomena or investigate a question. We discussed how scientists calculate data (ex. using eddy flux to measure NPP). Prior to this course, I had only focused on learning what a concept is (what is the definition of NPP?) and had never really thought about how we quantify/investigate that concept (how do we measure NPP of an ecosystem?)

3\) Systems thinking: I learned how to connect concepts and think about how they interact within a system (ex. we talked about how cold water affects decomposition rate. We connected this to metabolic rates of decomposers, noting that warmer temperatures increase decomposition rate. We then tied this to climate change and human activity. Warming water decreases the MRT of dissolved organic carbon in oceans as decomposers quickly use it up, leading to DOC getting respired to the atmosphere at a faster rate than normal.)
