---
title: "Weekly Reflections"
format: html
---

#### Reflection 1

While I'm unsure of what I'd like to do career wise, for the past couple of years I've explored different roles within ecosystem science to figure out what I like to do (so far forestry and a lab research position). I chose ESS because I knew that I liked science and have always been passionate about the environment, largely because I grew up exploring the great outdoors here in Colorado. As for content in class this week, I'd love to revisit the redfield ratio and talk about that a bit more in depth. I've learned about it in past ecology courses, but I think stoichiometric ratios are fundamental to ecology and would like to talk about this further.

#### Reflection 2

This week we covered topics including stoichiometry and modeling change in time of species' biomass using the house cat and grain scenario. We discussed assimilation and production efficiency, death rate, consumption (of grain by mice), predator feeding rate, etc. We also briefly talked about nutrient ratios and different types of photosynthesis. These are all concepts that I've been introduced to in former classes (intro ecology and ecosystem ecology), and although I feel like I have some grasp on how these mechanisms work and interact, hearing about them again after not having taken an ecology course in a while has shown me which concepts are easiest to recall (assimilation and production efficiency, death rates, etc.) and which are much harder for me to recall (stoichiometry, nutrient ratios, nutrient cycling). This helps me understand which concepts I need to review the most. 

#### Reflection 3

This week we discussed topics including the layers and composition of Earth's atmosphere, mean residence time, tropospheric & stratospheric ozone, CFCs & ozone, and UV-B impacts. I have discussed all of these topics in previous classes, but mean residence time is something that I am less familiar with and was a bit confused about. It seemed like Dr. Moore was saying that although the mean residence time of CO2 in the atmosphere is 5 yrs, it will take hundreds of years for that carbon to "cycle through" since inputs to the atmosphere from human release of CO2 have been so much greater than outputs from the atmosphere to carbon-fixing organisms. However, Dr. Moore brought up something about how the supply of CO2 is greater and therefore we would have more CO2 fixing organisms or something like that and that threw me off a bit. What is the implication of this?

#### Reflection 4

This week we focused on soil, including biological activity in soil, soil formation, weathering, etc. I've learned about soil a few times in different ecology/biology classes, but this is the first time that eluviation vs. illuviation has been explained to me in a way that I understand. I think soil health is often overlooked in its environmental importance, and I think that was made clear in class this week as we see that plants, our primary producers, depend on healthy soil. I also really enjoyed talking about cation-exchange capacity, as this is another concept that I've been introduced to but have never really understood. While I knew that it was a measure of soil fertility, I didn't understand the context. This week, I learned that root hairs can absorb cations through diffusion, and I guess I just never realized that cations are nutrients like Ca, K, and Mg until this week. 

#### Reflection 5

This week we discussed soil taxonomy, and the different classifications of soil based on traits like maturity, climate, parent material, etc. We also talked a bit about translocation and the different types of translocation that can occur in soil (ex. podzolization). We took our first exam this week and one thing that I noticed was that although I did not study much, I was able to draw on both what I've learned in this class as well as other classes to answer questions on the exam. Although I would've liked to have been able to go into more detail for some questions (the value of studying I suppose!), it was really encouraging to see that I really have learned a good amount about ecosystem science over the past couple years that I've been at CSU. Of course, there is still much for me to learn, but I often feel a sense of imposter syndrome...that is, I've made it far in school and done well, but I always question whether I truly know anything within this field or if I've just made it this far through brief memorization. This class (at least so far) almost feels like a culmination of things that I've learned throughout my ESS classes. While I've encountered almost every concept that we've discussed in this class in previous classes, I feel like this class is solidifying information that I only somewhat understand and showing me that I know more than I think I do. I hope I'm not saying all this in haste haha, hopefully I did well on the test. 

#### Reflection 6

This week we talked about several key concepts including: 1) RuBisCo, the most abundant enzyme, integral to the Calvin cycle. RuBisCo is not very efficient, but makes up for this in abundance. Tied to this is the concept of photorespiration. Both oxygen and CO2 can bind to RuBisCo, and when oxygen binds, the products are not useful to the plant for primary production. 2) Water use and nutrient use efficiency, which are measures that compare H2O and key nutrients like N to net photosynthesis. 3) NPP and NEP and how these are measured (leaf biomass, eddy co-variance flux, NDVI). 4) Soil fauna interactions, including rizosphere mutualisms, rizosphere trophic interactions, and litter layer interactions, all of which occur mostly in the O and A layers, sometimes all the way to the B layer depending on plant root depth.

#### Reflection 7

N/A

#### Reflection 8

This week we talked about succession and ecosystem development, and how traits differ between early and mature development stages. We also talked about mycorrhizal relationships and the role of enzymes in decomposition and soil carbon. Lastly, we started to talk about wetlands, and their importance for soil carbon storage. We were able to draw on concepts we've discussed in the past like mean residence time to understand wetland functions and attributes.

#### Reflection 9

This week we discussed biogeochemistry of wetlands, streams, and lakes. We talked about differences between aquatic and terrestrial ecosystems, and how aquatic ecosystems depend on the slow leakage of nutrients from terrestrial ecosystems (most nutrients are allocthonous). We talked about food web concepts including connectance, stability, and how changing diversity affects these measures. We also discussed properties of water and chemistry of common ions in water, anthropogenic effects on ions in water (ex. acid rain and sulfate ion), and stratification of lakes. We saw how stratified lakes have distinct layers where different processes occur (production in the epilimnion and decomposition in the hypolimnion), but connected how although these processes are spatially separated, they exhibit similar patterns to stream biogeochemistry.

#### Reflection 10

This week we compared trophic statuses of lakes (oligotrophic vs eutrophic) and discussed how human inputs can speed up a lakes' progression to a eutrophic state. We also talked about the paradox of enrichment, which asserts that simply adding nutrients to a system does not allow for unlimited growth as biogeochemical checks start to kick in. We reviewed the effects of different environmental variables on annual primary productivity in lakes, which related to concepts from ESS210 (physical geography). We also talked about estuaries and their biogeochemical processes including cation exchanges and flocculation.

#### Reflection 11

I think after our review session the thing that stood out to me most was Odum's framework. The table we looked at gave a breakdown of different attributes of an ecosystem (ex. rate of nutrient exchange between organisms and the environment) and how they compare between undeveloped and mature ecosystems. This table could be used to connect to pretty much any of the concepts we talked about over the past few weeks. I found myself referencing it a lot when thinking about things like connectance and species richness and their relationship, nutrient cycling and storage, etc.

#### Reflection 12

This week we talked about oceans and their circulation patterns, nutrient cycling, and decomposition of materials. We discussed how cold water slows the rate of decomposition, so a greater proportion of the products of primary productivity go to herbivores than decomposers compared to warmer surface waters. We discussed thermohaline circulation and the relationship between salt, temperature, and density, and how those all influence ocean circulation. We compared ocean nutrient cycling to lake/terrestrial cycling and noticed that the processes are the same, they're just on a much larger scale with higher MRTs in the ocean. 

#### Reflection 13

This week we continued our discussion on oceans, focusing on sea level rise, acidification, and the global hydrological cycle. We also talked about the cryosphere, glacial ice, and the Pleistocene Epoch (most recent ice age). We shifted gears to discuss the global carbon cycle and looked at how human activity (burning of fossil fuels, change in land use and land cover) are shifting fluxes in the carbon cycle. The model that we looked at showed how human activity is disrupting this cycle, and we observed that without human activity, the active carbon cycle seems to remain in equilibrium. We compared human activity fluxes to the burial rate (10 vs 0.1) and talked about how this relates to MRT. Even if we got rid of the human activity flux, it would take centuries to return to steady-state because the rate at which we've been releasing carbon to the atmosphere is so much higher than the burial rate. Our discussion on MRT also related to the paradox of enrichment. We talked about the worldview that adding more carbon to the atmosphere is like adding fertilizer since primary producers use CO2, however, at some point systems will reach a tipping point, becoming unstable and chaotic. Systems are complex, and by increasing availability to an energy source, we may see increases in productivity initially, however there are many other factors at play in ecosystem dynamics (the cat and mouse example helps us understand this, as increased mice population also means faster spread of disease). 

#### Reflection 14

This week we finished our discussion on the Arctic case study we looked at last week, examined the nitrogen cycle, and then began talking about the phosphorus cycle. One new thing that I learned this week was that phosphorous is quite abundant, but usable forms are hard to come by, especially in aquatic ecosystems. I noticed overlap between this class and NR400 this week. In this class, we talked about anthropogenic contributions to reactive N in the environment, and in NR400 we read an address from Cesar Chavez about grape vineyards and the connection between nitrate containing fertilizers leaching into waterways and sickness in nearby areas.

#### Reflection 15

This week we looked at SDGs and thought about how they relate to our GRFP proposals. I wrote my proposal on herbicide effects on soil microbes. I think my proposal most closely relates to SDG 15, Life on Land, as the purpose of my proposal is to protect microbial communities while accessing the benefits of herbicide use on invasive species. I also think that it relates to SDG 13, Climate Action. Indaziflam (the herbicide I included in my proposal) is used for cheatgrass management. Cheatgrass increases risk of wildfire. Coupled with aridification driven by climate change, risk of wildfire is amplified further. By managing cheatgrass cover, we mitigate a factor that could worsen a symptom of climate change, thus indaziflam use could be viewed as climate action. Although indaziflam is not directly addressing climate change, it is decreasing risk of a symptom caused by climate change. This then also relates to SDG 11, Sustainable Cities and Communities, as indaziflam use allows for adaptive climate management, protecting cities and communities from wildfire. 
